version: '3.8'

services:
  library-chatbox:
    build: 
      context: ./library-chatbox
    image: ${DOCKERHUB_USERNAME}/library-chatbox:latest
    container_name: library-chatbox
    ports:
      - "3000:3000"
    networks:
      - backend
  config-service:
    build:
      context: ./config-service
    image: ${DOCKERHUB_USERNAME}/config-service:latest
    container_name: config-service
    ports:
      - "8888:8888"
    networks:
      - backend
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - KAFKA_API_KEY=${KAFKA_API_KEY}
      - KAFKA_API_SECRET=${KAFKA_API_SECRET}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT}
      - SPRING_DATA_REDIS_PASSWORD=${SPRING_DATA_REDIS_PASSWORD}
      - SPRING_DATA_REDIS_TIMEOUT=${SPRING_DATA_REDIS_TIMEOUT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
  discovery-service:
      build:
        context: ./discovery-service
      image: ${DOCKERHUB_USERNAME}/discovery-service:latest
      container_name: discovery-service
      ports:
        - "8761:8761"
      networks:
        - backend
      depends_on:
        - config-service
      environment:
        - CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL}
        - SPRING_CLOUD_CONFIG_PROFILE=default
        - SPRING_CLOUD_CONFIG_LABEL=main
        - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
        - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
        - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
        - KAFKA_API_KEY=${KAFKA_API_KEY}
        - KAFKA_API_SECRET=${KAFKA_API_SECRET}
        - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
        - SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT}
        - SPRING_DATA_REDIS_PASSWORD=${SPRING_DATA_REDIS_PASSWORD}
        - SPRING_DATA_REDIS_TIMEOUT=${SPRING_DATA_REDIS_TIMEOUT}
        - EMAIL_USERNAME=${EMAIL_USERNAME}
        - EMAIL_PASSWORD=${EMAIL_PASSWORD}
  gateway-service:
    build:
      context: ./gateway-service
    image: ${DOCKERHUB_USERNAME}/gateway-service:latest
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - config-service
      - discovery-service
    environment:
      - CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL}
      - SPRING_CLOUD_CONFIG_PROFILE=default
      - SPRING_CLOUD_CONFIG_LABEL=main
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - KAFKA_API_KEY=${KAFKA_API_KEY}
      - KAFKA_API_SECRET=${KAFKA_API_SECRET}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT}
      - SPRING_DATA_REDIS_PASSWORD=${SPRING_DATA_REDIS_PASSWORD}
      - SPRING_DATA_REDIS_TIMEOUT=${SPRING_DATA_REDIS_TIMEOUT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

  user-service:
    build:
      context: ./user-service
    image: ${DOCKERHUB_USERNAME}/user-service:latest
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - config-service
      - discovery-service
    environment:
      - CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL}
      - SPRING_CLOUD_CONFIG_PROFILE=default
      - SPRING_CLOUD_CONFIG_LABEL=main
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - KAFKA_API_KEY=${KAFKA_API_KEY}
      - KAFKA_API_SECRET=${KAFKA_API_SECRET}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT}
      - SPRING_DATA_REDIS_PASSWORD=${SPRING_DATA_REDIS_PASSWORD}
      - SPRING_DATA_REDIS_TIMEOUT=${SPRING_DATA_REDIS_TIMEOUT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

  book-service:
    build:
      context: ./book-service
    image: ${DOCKERHUB_USERNAME}/book-service:latest
    container_name: book-service
    ports:
      - "8082:8082"
    networks:
      - backend
    depends_on:
      - config-service
      - discovery-service
    environment:
      - CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL}
      - SPRING_CLOUD_CONFIG_PROFILE=default
      - SPRING_CLOUD_CONFIG_LABEL=main
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - KAFKA_API_KEY=${KAFKA_API_KEY}
      - KAFKA_API_SECRET=${KAFKA_API_SECRET}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT}
      - SPRING_DATA_REDIS_PASSWORD=${SPRING_DATA_REDIS_PASSWORD}
      - SPRING_DATA_REDIS_TIMEOUT=${SPRING_DATA_REDIS_TIMEOUT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

  borrowing-service:
    build:
      context: ./borrowing-service
    image: ${DOCKERHUB_USERNAME}/borrowing-service:latest
    container_name: borrowing-service
    ports:
      - "8083:8083"
    networks:
      - backend
    depends_on:
      - config-service
      - discovery-service
    environment:
      - CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL}
      - SPRING_CLOUD_CONFIG_PROFILE=default
      - SPRING_CLOUD_CONFIG_LABEL=main
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - KAFKA_API_KEY=${KAFKA_API_KEY}
      - KAFKA_API_SECRET=${KAFKA_API_SECRET}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT}
      - SPRING_DATA_REDIS_PASSWORD=${SPRING_DATA_REDIS_PASSWORD}
      - SPRING_DATA_REDIS_TIMEOUT=${SPRING_DATA_REDIS_TIMEOUT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

  inventory-service:
    build:
      context: ./inventory-service
    image: ${DOCKERHUB_USERNAME}/inventory-service:latest
    container_name: inventory-service
    ports:
      - "8084:8084"
    networks:
      - backend
    depends_on:
      - config-service
      - discovery-service
    environment:
      - CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL}
      - SPRING_CLOUD_CONFIG_PROFILE=default
      - SPRING_CLOUD_CONFIG_LABEL=main
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - KAFKA_API_KEY=${KAFKA_API_KEY}
      - KAFKA_API_SECRET=${KAFKA_API_SECRET}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT}
      - SPRING_DATA_REDIS_PASSWORD=${SPRING_DATA_REDIS_PASSWORD}
      - SPRING_DATA_REDIS_TIMEOUT=${SPRING_DATA_REDIS_TIMEOUT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

  notification-service:
    build:
      context: ./notification-service
    image: ${DOCKERHUB_USERNAME}/notification-service:latest
    container_name: notification-service
    ports:
      - "8085:8085"
    networks:
      - backend
    environment:
      - CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL}
      - SPRING_CLOUD_CONFIG_PROFILE=default
      - SPRING_CLOUD_CONFIG_LABEL=main
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - KAFKA_API_KEY=${KAFKA_API_KEY}
      - KAFKA_API_SECRET=${KAFKA_API_SECRET}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT}
      - SPRING_DATA_REDIS_PASSWORD=${SPRING_DATA_REDIS_PASSWORD}
      - SPRING_DATA_REDIS_TIMEOUT=${SPRING_DATA_REDIS_TIMEOUT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

    depends_on:
      - config-service
      - discovery-service

networks:
  backend:
    driver: bridge
